// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin-cr7m10vk18msd7r45n16" | "/admin-cr7m10vk18msd7r45n16/login" | "/blogs" | "/blogs/[slug]" | "/blogs/category/[category]" | "/book" | "/contact" | "/privacy" | "/services" | "/services/[slug]" | "/terms" | "/testimonials"
type AppRouteHandlerRoutes = "/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/get-bookings" | "/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/update-status" | "/api/admin-login" | "/api/bookings" | "/api/contact" | "/api/enquiries" | "/api/verify-captcha"
type PageRoutes = never
type LayoutRoutes = "/" | "/about" | "/admin-cr7m10vk18msd7r45n16" | "/blogs" | "/book" | "/contact" | "/services" | "/testimonials"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin-cr7m10vk18msd7r45n16": {}
  "/admin-cr7m10vk18msd7r45n16/login": {}
  "/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/get-bookings": {}
  "/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/update-status": {}
  "/api/admin-login": {}
  "/api/bookings": {}
  "/api/contact": {}
  "/api/enquiries": {}
  "/api/verify-captcha": {}
  "/blogs": {}
  "/blogs/[slug]": { "slug": string; }
  "/blogs/category/[category]": { "category": string; }
  "/book": {}
  "/contact": {}
  "/privacy": {}
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/terms": {}
  "/testimonials": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about": never
  "/admin-cr7m10vk18msd7r45n16": never
  "/blogs": never
  "/book": never
  "/contact": never
  "/services": never
  "/testimonials": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
