// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(public)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/blogs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/blogs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/blogs/category/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blogs/category/[category]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/blogs/category/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blogs">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/book">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/testimonials">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-cr7m10vk18msd7r45n16/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-cr7m10vk18msd7r45n16/login">> = Specific
  const handler = {} as typeof import("../../src/app/admin-cr7m10vk18msd7r45n16/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-cr7m10vk18msd7r45n16/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-cr7m10vk18msd7r45n16">> = Specific
  const handler = {} as typeof import("../../src/app/admin-cr7m10vk18msd7r45n16/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/get-bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/get-bookings">> = Specific
  const handler = {} as typeof import("../../src/app/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/get-bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/update-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/update-status">> = Specific
  const handler = {} as typeof import("../../src/app/admin-dfhfvjhzbdsvhjzdgvbjhzbdv/update-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/enquiries/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enquiries">> = Specific
  const handler = {} as typeof import("../../src/app/api/enquiries/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/verify-captcha/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verify-captcha">> = Specific
  const handler = {} as typeof import("../../src/app/api/verify-captcha/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(public)/about/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/about/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/blogs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blogs">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/blogs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/book/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/book">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/book/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/services/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/services/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(public)/testimonials/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/testimonials">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/testimonials/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin-cr7m10vk18msd7r45n16/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin-cr7m10vk18msd7r45n16">> = Specific
  const handler = {} as typeof import("../../src/app/admin-cr7m10vk18msd7r45n16/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
