var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/privacy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__02d8ymk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_01.b12w.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ecbxq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xugv19._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_0lljva0._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_privacy_page_actions_071~-w_.js")
R.m(65384)
module.exports=R.m(65384).exports
