var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin-cr7m10vk18msd7r45n16/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__091j2xf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0kfurv~.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ecbxq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xugv19._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_app_admin-cr7m10vk18msd7r45n16_layout_tsx_0b3i.x4._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin-cr7m10vk18msd7r45n16_page_actions_054h3rm.js")
R.m(45446)
module.exports=R.m(45446).exports
