var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/services/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__057ev1i._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0fhydo1.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_lucide-react_dist_esm_0xi1jkw._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ecbxq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xugv19._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_0lljva0._.js")
R.c("server/chunks/ssr/src_app_(public)_services_layout_tsx_046kcps._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_services_page_actions_0d5x5e..js")
R.m(62453)
module.exports=R.m(62453).exports
