var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/book/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kjzp.f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_02.x04~.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ecbxq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xugv19._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_0lljva0._.js")
R.c("server/chunks/ssr/src_app_(public)_book_layout_tsx_09v_r9_._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_book_page_actions_10qsq9u.js")
R.m(24786)
module.exports=R.m(24786).exports
