var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/testimonials/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0~1xct.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_11cn58s.js")
R.c("server/chunks/ssr/node_modules_next_dist_09jzzl8._.js")
R.c("server/chunks/ssr/node_modules_lucide-react_dist_esm_0xi1jkw._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ecbxq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__098zro9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xugv19._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_0zcs5pf._.js")
R.c("server/chunks/ssr/src_0lljva0._.js")
R.c("server/chunks/ssr/src_app_(public)_testimonials_layout_tsx_0c64fst._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_testimonials_page_actions_0xbjebr.js")
R.m(36869)
module.exports=R.m(36869).exports
